version: 2.1

executors:
  with-chrome:
    docker:
      - image: cypress/browsers:chrome69

orbs:
  cypress: cypress-io/cypress@1.9.0

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          record: true
          start: npm start
          wait-on: 'http://localhost:8000'
